"""Launchpad Pro 128-color palette + RGB->index quantizer.

The exact 128 RGB triples emitted by the LP Pro MK1 firmware live in the
Programmer's Reference Guide color chart. The table below is a reasonable
synthetic approximation organized so that nearest-RGB matches produce
plausible results across the gamut. For pixel-perfect color, replace the
table with values measured from the actual device.
"""
from __future__ import annotations

from functools import lru_cache

import numpy as np

from launch_lights.engine.frame import RGB


def _build_palette() -> tuple[tuple[int, int, int], ...]:
    """Return 128 (r, g, b) triples with r,g,b in 0..63.

    Layout:
      0     : off
      1-3   : grays (dim, mid, bright)
      4-127 : 124 hues x values; generated by a hue x brightness lattice
              that maximises spread in linearized RGB space.
    """
    entries: list[tuple[int, int, int]] = [(0, 0, 0), (20, 20, 20), (38, 38, 38), (63, 63, 63)]

    # Generate 124 entries: 31 hues * 4 brightness levels
    n_hues = 31
    levels = (16, 32, 48, 63)
    for v in levels:
        for h_step in range(n_hues):
            h = h_step / n_hues
            r, g, b = _hsv_to_rgb(h, 1.0, v / 63.0)
            entries.append((int(round(r * 63)), int(round(g * 63)), int(round(b * 63))))
    assert len(entries) == 128
    return tuple(entries)


def _hsv_to_rgb(h: float, s: float, v: float) -> tuple[float, float, float]:
    i = int(h * 6.0)
    f = h * 6.0 - i
    p = v * (1.0 - s)
    q = v * (1.0 - f * s)
    t = v * (1.0 - (1.0 - f) * s)
    i %= 6
    if i == 0:
        return v, t, p
    if i == 1:
        return q, v, p
    if i == 2:
        return p, v, t
    if i == 3:
        return p, q, v
    if i == 4:
        return t, p, v
    return v, p, q


LAUNCHPAD_PALETTE_RGB: tuple[tuple[int, int, int], ...] = _build_palette()


class Palette:
    """Precomputed 64^3 RGB -> nearest-palette-index LUT (256 KB)."""

    def __init__(self, table: tuple[tuple[int, int, int], ...] = LAUNCHPAD_PALETTE_RGB) -> None:
        self.table = np.asarray(table, dtype=np.int16)  # (128, 3)
        self._lut = _build_nearest_lut(self.table)  # (64, 64, 64) uint8

    def nearest(self, rgb: RGB) -> int:
        return int(self._lut[rgb.r, rgb.g, rgb.b])

    def index_to_rgb(self, idx: int) -> RGB:
        r, g, b = self.table[idx]
        return RGB(int(r), int(g), int(b))


@lru_cache(maxsize=1)
def _build_nearest_lut(table_bytes: tuple) -> np.ndarray:
    """Cached by table identity (passed as a tuple-hashable). Returns shape
    (64, 64, 64) uint8 indexing into the palette."""
    return _build_nearest_lut_impl(np.asarray(table_bytes, dtype=np.int16))


def _build_nearest_lut_impl(table: np.ndarray) -> np.ndarray:
    """Build (64,64,64) uint8 LUT mapping (r,g,b) -> palette index.

    Vectorized: enumerate all 64^3 = 262144 candidate RGBs, compute squared
    Euclidean distance to each of 128 palette entries (weighted to favor
    green per the Y channel of Rec.601), pick the argmin.
    """
    rr, gg, bb = np.mgrid[0:64, 0:64, 0:64]
    pixels = np.stack([rr, gg, bb], axis=-1).astype(np.int32)  # (64,64,64,3)
    pixels_flat = pixels.reshape(-1, 3)  # (N, 3)

    # weighted squared distance to each palette entry
    # Rec.601-ish luminance weights, scaled
    w = np.array([0.30, 0.59, 0.11], dtype=np.float32)
    diffs = (pixels_flat[:, None, :].astype(np.float32) - table[None, :, :].astype(np.float32))
    sq = (diffs * diffs) * w
    dist2 = sq.sum(axis=2)  # (N, 128)
    idx = np.argmin(dist2, axis=1).astype(np.uint8)
    return idx.reshape(64, 64, 64)


# Wrap _build_nearest_lut to accept np.ndarray (the lru_cache wants hashable)
def _build_nearest_lut_wrapper(table: np.ndarray) -> np.ndarray:
    return _build_nearest_lut_impl(table)


# Bypass the lru_cache decorator for the public function; cache via a
# module-level dict keyed by id() of the table for speed at call time.
_lut_cache: dict[int, np.ndarray] = {}


def _build_nearest_lut(table: np.ndarray) -> np.ndarray:  # noqa: F811
    key = id(table)
    if key not in _lut_cache:
        _lut_cache[key] = _build_nearest_lut_impl(table)
    return _lut_cache[key]
